window.CarouselConfig = {
    "title": "Carousel",
    "dataset": [
        {
            "id": "default",
            "title": "Основной",
            "default": true,
            "active": true,
            "source": [
                "data/animal/001.jpg",
                "data/animal/002.jpg",
                "data/animal/301.jpg",
                "data/animal/302.jpg",
                "data/animal/303.jpg",
                "data/animal/304.jpg",
                "data/animal/305.jpg",
                "data/animal/306.jpg",
                "data/animal/307.jpg",
                "data/animal/308.jpg",
                "data/animal/309.jpg",
                "data/animal/310.jpg",
                "data/smile/001.jpg",
                "data/smile/002.jpg",
                "data/smile/003.jpg",
                "data/smile/004.jpg",
                "data/smile/005.jpg",
                "data/smile/006.jpg",
                "data/smile/007.jpg",
                "data/smile/008.jpg",
                "data/smile/009.jpg",
                "data/smile/010.jpg",
                "data/smile/011.jpg",
                "data/smile/012.jpg",
                "data/smile/013.jpg",
                "data/smile/014.jpg",
                "data/smile/015.jpg",
                "data/smile/016.jpg",
                "data/smile/017.jpg",
                "data/smile/018.jpg",
                "data/smile/019.jpg",
                "data/smile/020.jpg",
                "data/smile/021.jpg",
                "data/smile/201.jpg",
                "data/smile/202.jpg",
                "data/smile/203.jpg",
                "data/smile/205.jpg",
                "data/smile/206.jpg",
                "data/smile/207.jpg",
                "data/sad/sad.jpg"
            ]
        },
        {
            "id": "animals",
            "title": "Животные",
            "active": true,
            "order": 1,
            "source": [
                "data/animal/001.jpg",
                "data/animal/002.jpg",
                "data/animal/301.jpg",
                "data/animal/302.jpg",
                "data/animal/303.jpg",
                "data/animal/304.jpg",
                "data/animal/305.jpg",
                "data/animal/306.jpg",
                "data/animal/307.jpg",
                "data/animal/308.jpg",
                "data/animal/309.jpg",
                "data/animal/310.jpg"
            ]
        }
    ]
};